//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUT.Gplex.IncludeResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QUT.Gplex.IncludeResources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a     [Serializable]
        ///    public class BufferException : Exception
        ///    {
        ///        public BufferException() { }
        ///        public BufferException(string message) : base(message) { }
        ///        public BufferException(string message, Exception innerException)
        ///            : base(message, innerException) { }
        ///        protected BufferException(SerializationInfo info, StreamingContext context)
        ///            : base(info, context) { }
        ///    }
        ///
        ///    public abstract class ScanBuff
        ///    {
        ///        private string fileNm;
        ///
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string GplexBuffers {
            get {
                return ResourceManager.GetString("GplexBuffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a //
        ///// Revised backup code
        ///// Version 1.2.1 of 24-June-2013
        /////
        ///## Derived from gplex.frame version of 2-September-2006.
        ///## Code page support for files without a BOM. 
        ///## Left and Right Anchored state support.
        ///## Start condition stack. Two generic params.
        ///## Using fixed length context handling for right anchors
        /////
        ///##--&gt;defines
        ///
        ///using System;
        ///using System.IO;
        ///using System.Text;
        ///using System.Globalization;
        ///using System.Collections.Generic;
        ///using System.Runtime.Serialization;
        ///using System.Diagn [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string GplexxFrame {
            get {
                return ResourceManager.GetString("GplexxFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a // ==============================================================
        ///// &lt;auto-generated&gt;
        ///// This code automatically produced from an embedded resource.
        ///// Do not edit this file, or it will become incompatible with 
        ///// the specification from which it was generated.
        ///// &lt;/auto-generated&gt;
        ///// ==============================================================
        ///.
        /// </summary>
        internal static string ResourceHeader {
            get {
                return ResourceManager.GetString("ResourceHeader", resourceCulture);
            }
        }
    }
}
